meta_product_name: "Expo-buddy"
meta_title: "Expo-buddy - Product tagline"
meta_description: "Organize all your expos and exhibitor information - in just one single app!"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
