meta_product_name: "Expo-buddy"
meta_title: "Expo-buddy - Organize all your expos and exhibitor information in just one single app!"
meta_description: "Browse through all relevant expos and exhibitors in consumer eletronics with just one single app. Welcome to the 21st century: Take your notes digitally and save them with the respective exhibitors that you visited. Export all your notes from the app into a file and attach them to the CRM system of your choice."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
